name: "CI"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "npm"
          node-version: "16"

      - name: "Install dependencies"
        run: "npm install"

      - name: "Compile and generate Typechain bindings"
        run: "npx hardhat typechain"

      - name: "Run tests"
        run: "npx hardhat test"

      - name: "Run gas reports"
        run: "REPORT_GAS=true npx hardhat tests"